services:
  - type: web
    name: road-safety
    env: python
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
